### ISSUE TITLE
Increase the Gas Limit per Transaction

### ISSUE THREAD

**Issue by mrtpain** [stratisproject/CirrusSmartContracts#30]
This request is to increase the gas limit per transaction from the current `100,000` limit. 

## Why
In many DEFI/ETH contracts, there are several contract calls made for just 1 transaction. Eth has a gas limit per block, not per transaction which allows for more calls in a single transaction without throwing an exception. 

An example of this is Uniswap contracts, that can make on average about 8-10 calls for a single hop swap. Multi-hop swaps add even more to this amount on calls between contracts for a single transaction.

Stratis Smart Contracts costs `10,000` gas to call another contract, 10% of the total gas limit. There is only enough to do about 7 calls per transaction safely when considering other gas costs of methods. 

This heavily limits the amount of work / integrations that can work with Stratis Smart Contracts. 

## Proposal
At minimum, double the Gas Limit per transaction to `200,000`. Thinking longer term, DEFI, and Stratis Smart Contract integrations, `250,000` - `500,000` would be a better limit however, I realize this may reduce the Cirrus TPS amongst other things.

**Comment by quantumagi** [comment]
We could increase the maximum per-transaction gas consumption while limiting the sum of gas spent in a block. 

Some considerations:
- Would it be beneficial for each transaction to declare its own maximum gas consumption. How to we prevent over-estimation?
- Having a block limit is good in the sense that it places an upper limit on the amount of CPU work to be done per block.
- The block gas limit could be a constant or dynamic just as block or round times could be dynamic.
- It will require changes to how we build blocks. We would need to use knowledge about the maximum gas consumption of each transaction to determine which transactions we can be included in a block so as not to exceed the block limit.
- Dynamically increasing gas costs can be used to increase Cirrus TPS.

**Comment by mrtpain** [comment]
Closing, this has been taken care of raising the maximum gas per transaction to 250,000 from 100,000
